version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget.exe restore ValidateFastaFiles.sln
configuration: Release
platform: Any CPU
build:
  project: ValidateFastaFiles.sln
  verbosity: minimal
artifacts:
- path: bin
  name: Validate-Fasta-File